import type { Metadata } from "next";
import Link from "next/link";
import LegalPage, { Clause } from "@/components/site/LegalPage";
import { getSettings } from "@/lib/catalog";

export const metadata: Metadata = {
  title: "Privacy Policy | Tripwaley",
  description:
    "How Tripwaley collects, uses, shares, stores and protects your personal data, your rights over it, and how to reach our Grievance Officer.",
};

const UPDATED = "2026-08-28";

/* PRIVACY POLICY.
 *
 * Rewritten to satisfy Indian statutory review (payment gateways check this
 * before activating a merchant). The earlier version was accurate but written
 * only for travellers, and was rejected for missing the clauses a reviewer
 * looks for by name: the IT Act 2000 electronic-record framing, the
 * data-localisation statement, express consent AND withdrawal of consent,
 * retention/deletion, the sensitive-personal-data and fraud-warning language,
 * the transmission-security acknowledgement, and — the mandatory one — a
 * published Grievance Officer (Rule 5(9), SPDI Rules 2011).
 *
 * It is deliberately NOT the generic template a gateway hands out: that one
 * describes couriers, perishable goods and returns, none of which are true
 * here. Claiming practices we don't follow would be its own compliance
 * problem, so the statutory scaffolding is kept and the substance describes
 * what Tripwaley actually does.
 */
export default function PrivacyPage() {
  const s = getSettings();
  const entity = s.legalName || s.brand;

  return (
    <LegalPage
      kicker="your data, plainly explained"
      title="Privacy Policy"
      updated={UPDATED}
      grievance
      intro={`How ${entity} collects, uses, shares, stores and protects your personal data when you browse www.tripwaley.com or book a trip — and the rights you have over it.`}
    >
      <Clause n={1} title="About this document">
        <p>
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules
          made thereunder, as applicable, and the amended provisions pertaining to electronic records in
          various statutes as amended by the Information Technology Act, 2000. This electronic record is
          generated by a computer system and does not require any physical or digital signature.
        </p>
        <p>
          This document is published in accordance with the provisions of Rule 3(1) of the Information
          Technology (Intermediaries Guidelines) Rules, 2011, which require publishing the rules and
          regulations, privacy policy and terms of use for access to or usage of{" "}
          <strong>www.tripwaley.com</strong>{" "}
          (the &ldquo;Platform&rdquo;), including any related mobile site
          or application.
        </p>
        <p>
          The Platform is owned and operated by <strong>{entity}</strong>
          {s.entityType ? <>, {s.entityType}</> : null}
          {s.address ? <>, having its principal place of business at {s.address}</> : null}{" "}
          (referred to as &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo; or &ldquo;{s.brand}&rdquo;)
          {s.udyam ? <>. Udyam registration number: {s.udyam}</> : null}
          {s.gstin ? <>. GSTIN: {s.gstin}</> : null}.
        </p>
      </Clause>

      <Clause n={2} title="Scope, and where your data lives">
        <p>
          You may browse certain sections of the Platform without registering with us. We do not offer any
          product or service under this Platform outside India, and{" "}
          <strong>your personal data is primarily stored and processed in India</strong>.
        </p>
        <p>
          By visiting this Platform, providing your information, or availing any product or service offered
          on the Platform, you expressly agree to be bound by this Privacy Policy and our{" "}
          <Link href="/terms">Terms &amp; Conditions</Link>, and agree to be governed by the laws of India,
          including the laws applicable to data protection and privacy. If you do not agree, please do not
          use or access our Platform.
        </p>
      </Clause>

      <Clause n={3} title="Information we collect">
        <p>
          We collect your personal data when you use the Platform, book a trip, or otherwise interact with us
          during the course of our relationship. What we collect includes, but is not limited to:
        </p>
        <ul>
          <li>
            <strong>Identity and contact data</strong> — name, mobile number, email address, boarding city,
            and (where a permit or a stay legally requires it) government-issued ID details such as Aadhaar,
            passport or voter ID particulars.
          </li>
          <li>
            <strong>Booking data</strong> — the trip, departure date, occupancy, traveller count, emergency
            contact, and any dietary, medical or accessibility needs you choose to disclose.
          </li>
          <li>
            <strong>Sensitive personal data</strong> — collected only with your consent and only where
            necessary, for example payment instrument details processed by our payment gateway.
          </li>
          <li>
            <strong>Technical and behavioural data</strong> — pages viewed, approximate location derived from
            your IP address, device and browser type, and how you reached the Platform. This is compiled and
            analysed largely on an aggregated basis.
          </li>
        </ul>
        <p>
          You always have the option not to provide information, by choosing not to use a particular service
          or feature on the Platform. Where a permit or a statutory requirement makes a particular detail
          mandatory, we will tell you at the point of collection, and your booking for that route may not be
          possible without it.
        </p>
      </Clause>

      <Clause n={4} title="A warning about fraud">
        <p>
          <strong>
            We will never ask you for your card PIN, CVV, net-banking password, UPI PIN or any one-time
            password (OTP).
          </strong>{" "}
          If you receive a call, message or email from a person claiming to be from {s.brand} asking for any
          of these, do not share them. If you have already shared such information, report it immediately to
          your bank and to the appropriate law-enforcement agency, and tell us so we can assist.
        </p>
      </Clause>

      <Clause n={5} title="How we use your information">
        <p>We use personal data to provide the services you request. Specifically, to:</p>
        <ul>
          <li>confirm, operate and service your booking — seats, stays, transport and permits;</li>
          <li>contact you about your trip, including the WhatsApp group for your batch;</li>
          <li>process payments and issue refunds through our payment gateway;</li>
          <li>resolve disputes, troubleshoot problems and respond to your requests;</li>
          <li>detect, prevent and protect against error, fraud and other criminal activity;</li>
          <li>comply with our legal obligations, including permit, tax and record-keeping requirements;</li>
          <li>conduct research and analysis to improve the Platform and our trips;</li>
          <li>
            inform you about offers, departures and updates — where we use your data to market to you, you
            can opt out at any time, and doing so never affects messages about a live booking.
          </li>
        </ul>
      </Clause>

      <Clause n={6} title="Who we share it with">
        <p>We share only what a recipient genuinely needs in order to do its job:</p>
        <ul>
          <li>
            <strong>Trip suppliers</strong> — the stays, transport operators, guides and permit authorities on
            your specific itinerary receive the traveller names and ID particulars they are legally required
            to hold.
          </li>
          <li>
            <strong>Payment gateways and prepaid payment instrument issuers</strong> — to process your payment
            and any refund. They handle your payment credentials directly and act under their own privacy
            policies and RBI regulation.
          </li>
          <li>
            <strong>Technology and analytics providers</strong> — including Google Analytics and Meta Pixel,
            described in clause 8.
          </li>
          <li>
            <strong>Government agencies and law enforcement</strong> — where required by law, or in good-faith
            belief that disclosure is reasonably necessary to respond to a summons, court order or other
            legal process, to enforce our Terms of Use, or to protect the rights, property or personal safety
            of our users or the public.
          </li>
        </ul>
        <p>
          <strong>We do not sell your personal data.</strong> We do not share your phone number with other
          travellers without your consent.
        </p>
      </Clause>

      <Clause n={7} title="Security precautions">
        <p>
          To protect your personal data from unauthorised access, disclosure, loss or misuse, we adopt
          reasonable security practices and procedures. The Platform is served only over encrypted HTTPS
          connections, administrative access requires an authenticated signed session, and payment
          credentials are handled by our payment gateway and are never stored on our servers.
        </p>
        <p>
          However, the transmission of information over the internet is not completely secure for reasons
          beyond our control. By using the Platform you accept the security implications of data transmission
          over the internet, which cannot always be guaranteed as completely secure, and accept that certain
          inherent risks therefore remain. You are responsible for protecting any login credentials
          associated with your account.
        </p>
      </Clause>

      <Clause n={8} title="Cookies, analytics and advertising">
        <p>
          We use cookies for essential functions, such as remembering your chosen boarding city between
          pages. We also use <strong>Google Analytics</strong> for aggregate statistics about how the
          Platform is used, and the <strong>Meta Pixel</strong> to measure advertising performance.
        </p>
        <p>
          You can block these through your browser settings, an ad blocker, or your device&apos;s
          ad-tracking controls. Blocking them does not affect your ability to browse or to book.
        </p>
      </Clause>

      <Clause n={9} title="Data retention and deletion">
        <p>
          We retain your personal data for no longer than is required for the purpose for which it was
          collected, or as required under applicable law — whichever is longer. In practice:
        </p>
        <ul>
          <li>
            <strong>Booking and payment records</strong> are retained for as long as tax, permit and
            accounting law requires.
          </li>
          <li>
            <strong>Enquiries that did not become bookings</strong> are retained for up to 24 months and then
            deleted.
          </li>
          <li>
            <strong>Analytics data</strong> is retained for the period configured in the analytics platform.
          </li>
        </ul>
        <p>
          You may request deletion of your personal data by writing to our Grievance Officer using the
          details published below. Once deleted, you will lose access to any information associated with it.
          We may refuse or delay deletion where there is a pending grievance, claim, booking or payment, or
          where retention is necessary to prevent fraud or future abuse, or is required by law. We may
          continue to retain data in anonymised form for analytical and research purposes.
        </p>
      </Clause>

      <Clause n={10} title="Your rights">
        <p>You may at any time ask us to:</p>
        <ul>
          <li>tell you what personal data we hold about you;</li>
          <li>correct or update anything that is inaccurate;</li>
          <li>delete your data, subject to clause 9;</li>
          <li>stop sending you marketing communications.</li>
        </ul>
        <p>
          Write to our Grievance Officer using the details below. We respond within 30 days, and there is no
          charge for a reasonable request.
        </p>
      </Clause>

      <Clause n={11} title="Consent, and withdrawing it">
        <p>
          By visiting the Platform or providing your information, you consent to the collection, use,
          storage, disclosure and other processing of your information in accordance with this Privacy
          Policy. If you disclose to us personal data relating to other people — for example other travellers
          in your group — you represent that you have their authority to do so.
        </p>
        <p>
          You consent to us contacting you by SMS, WhatsApp or other instant-messaging apps, telephone call
          and email for the purposes described in this Privacy Policy.
        </p>
        <p>
          <strong>You may withdraw your consent at any time</strong> by writing to the Grievance Officer
          named below. A withdrawal is not retrospective. Where you withdraw consent for information we
          consider necessary to provide a service, we reserve the right to restrict or decline that service —
          for example, we cannot operate a permitted-area trip without the ID details the permit requires.
        </p>
      </Clause>

      <Clause n={12} title="Children">
        <p>
          The Platform is not directed at children under 18, and we do not knowingly collect their personal
          data except as part of a booking made by a parent or guardian for travellers in their care.
        </p>
      </Clause>

      <Clause n={13} title="Changes to this Privacy Policy">
        <p>
          Please review this Privacy Policy periodically. We may update it to reflect changes to our
          information practices or to the law, and we will notify you of significant changes in the manner
          required under applicable law. The last-updated date is shown at the top of this page.
        </p>
      </Clause>
    </LegalPage>
  );
}
